events {
    worker_connections 1024;
}

http {
    # [VULN] server_tokens not disabled — nginx version exposed in headers
    # server_tokens off;

    upstream juiceshop {
        server 10.10.1.20:3000;
    }

    server {
        listen 80;
        server_name _;

        # [VULN] no rate limiting block defined — brute-force possible on login
        # limit_req_zone $binary_remote_addr zone=login:10m rate=5r/m;

        location / {
            proxy_pass http://juiceshop;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            # [VULN] no security headers set
            # add_header X-Frame-Options "SAMEORIGIN";
            # add_header X-Content-Type-Options "nosniff";
            # add_header Content-Security-Policy "default-src 'self'";
        }
    }
}
